window.jQuery = window.$ = require('jquery');
require('jquery-validation');
require('./jquery.modal');
require('./ug-theme-tiles.js');
require('./unitegallery.min.js');
window.angular = require('angular');
require('angular-route');
require('angular-ui-router');
require('jpkleemans-angular-validate');
require('ngStorage');
require('angular-base64');